In [1]:
import cx_Oracle
import random
from datetime import datetime
from datetime import timedelta

In [2]:
# Connection details
username = 'airlinecompany_dwh'
password = '123'
hostname = 'localhost'
port = '1521'
service_name = 'XE'

# Connect to the database
connection = cx_Oracle.connect(username, password, hostname + ':' + port + '/' + service_name)
cursor = connection.cursor()

connection

In [93]:

# '''# Function to generate random alphanumeric strings
# def random_string(length):
#     letters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
#     return ''.join(random.choice(letters) for i in range(length))'''

# # Function to generate random dates within a range
# def random_date(start_date, end_date):
#     return start_date + timedelta(seconds=random.randint(0, int((end_date - start_date).total_seconds())))


# # Function to generate random dates within a range
# def random_date(start_date, end_date):
#     return start_date + timedelta(days=random.randint(0, (end_date - start_date).days))

In [96]:
from datetime import date, timedelta

# Populate Date Dimension
'''
start_date = date(2015, 1, 1)  # Start date
end_date = date(2030, 1, 1)   # End date

for i in range((end_date - start_date).days + 1):
    datee = start_date + timedelta(days=i)
    date_key = int(datee.strftime('%Y%m%d'))
    day_of_week = datee.strftime('%A')
    day_number_in_epoch = (datee - start_date).days + 1
    week_number_in_epoch = (datee - start_date).days // 7 + 1
    month_number_in_epoch = (datee.year - start_date.year) * 12 + datee.month - start_date.month + 1
    day_number_in_calendar_month = datee.day
    day_number_in_calendar_year = (datee - date(datee.year, 1, 1)).days + 1
    calendar_month = datee.strftime('%B')
    calendar_month_number_in_year = datee.month
    calendar_year_month = datee.strftime('%Y-%m')
    calendar_quarter = f'Q{((datee.month - 1) // 3) + 1}'
    calendar_year_quarter = f'{datee.year}-Q{((datee.month - 1) // 3) + 1}'
    calendar_year = datee.year
    fiscal_month = calendar_month
    fiscal_month_number_in_year = calendar_month_number_in_year
    fiscal_year_month = calendar_year_month
    fiscal_quarter = calendar_quarter
    fiscal_year_quarter = calendar_year_quarter
    fiscal_year = calendar_year
    
    cursor.execute("INSERT INTO Date_DimensionT VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11, :12, :13, :14, :15, :16, :17, :18, :19, :20)", 
                   (date_key, datee, day_of_week, day_number_in_epoch, week_number_in_epoch, month_number_in_epoch, day_number_in_calendar_month, day_number_in_calendar_year, calendar_month, calendar_month_number_in_year, calendar_year_month, calendar_quarter, calendar_year_quarter, calendar_year, fiscal_month, fiscal_month_number_in_year, fiscal_year_month, fiscal_quarter, fiscal_year_quarter, fiscal_year))
connection.commit()'''

In [4]:

import itertools
import random
# Interaction_DimensionT

interaction_types = ['inquiries', 'complaints', 'feedback']
interaction_channels = ['phone', 'email', 'chat', 'in-person']
sentiments = ['positive', 'neutral', 'negative']
ratings = list(range(1, 6))  # Ratings from 1 to 5
interaction_phases = ['before', 'after', 'within']
interaction_severity = ['Top Urgent', 'Urgent', 'Mild', 'Normal']

# Get all possible combinations of interaction attributes
combinations = list(itertools.product(interaction_types, interaction_channels, sentiments, ratings, interaction_phases, interaction_severity))

# Populate Interaction Dimension
for index, combination in enumerate(combinations, start=1):
    interaction_id = index
    interaction_type, interaction_channel, sentiment, rating, interaction_phase, severity = combination
    cursor.execute("INSERT INTO Interaction_DimensionT VALUES (:1, :2, :3, :4, :5, :6, :7)", 
                   (interaction_id, interaction_type, interaction_channel, sentiment, rating, interaction_phase, severity))

# Commit changes to the database
connection.commit()

In [49]:
# Populate Ancillary Service DimensionT

'''import itertools

# Define the possible values for ancillary service attributes
service_names = ['meal', 'wifi', 'extra luggage', 'seat selection']
service_classes = ['economy', 'business', 'first']

# Get all possible combinations of ancillary service attributes
combinations = list(itertools.product(service_names, service_classes))

# Populate Ancillary Service Dimension
for index, combination in enumerate(combinations, start=1):
    service_name, service_class = combination
    ancillary_service_key = index
    ancillary_service_number = ancillary_service_key  # Using the key as the service number
    service_cost = random.uniform(10, 100)
    service_description = f'Description for Ancillary Service {ancillary_service_number}'
    cursor.execute("INSERT INTO Ancillary_Service_DimensionT VALUES (:1, :2, :3, :4, :5, :6)", 
               (ancillary_service_key, ancillary_service_number, service_name, service_class, service_cost, service_description))

# Commit changes to the database
connection.commit()'''

In [50]:
# Populate Main Service Dimension

# Populate Main Service Dimension
'''for i, main_service_name in enumerate(['Booking', 'Ticketing', 'Refunding', 'baggage'], start=1):
    main_service_key = i
    main_service_number = random.randint(100, 999)
    cursor.execute("INSERT INTO Main_Service_DimensionT VALUES (:1, :2, :3)", 
                   (main_service_key, main_service_number, main_service_name))

# Commit changes to the database
connection.commit()'''

In [90]:
import itertools
#Passenger_Profile_Dim
'''
frequent_flyer_tiers = ['Gold', 'Platinum', 'Titanium']
club_membership_statuses = ['Premium', 'Standard']
lifetime_mileage_tiers = ['Under 100,000 miles', '100,000-499,999 miles', '500,000-999,999 miles', '1,000,000-1,999,999 miles', '2,000,000+ miles']
home_airports = ['AIR001', 'AIR002', 'AIR003', 'AIR004']
# Get unique combinations of frequent flyer elite tier, home airport, club membership status, and lifetime mileage tier
combinations = list(itertools.product(frequent_flyer_tiers, home_airports, club_membership_statuses, lifetime_mileage_tiers))

# Populate Passenger Profile Dimension
for index, combination in enumerate(combinations, start=1):
    frequent_flyer_tier, home_airport, club_membership_status, lifetime_mileage_tier = combination
    passenger_profile_key = index
    cursor.execute("INSERT INTO Passenger_Profile_DimT VALUES (:1, :2, :3, :4, :5)", 
                   (passenger_profile_key, frequent_flyer_tier, home_airport, club_membership_status, lifetime_mileage_tier))
connection.commit()
'''

In [60]:
#Class_Of_Service_Flown_DimT

'''fare_classes = ['Economy', 'prem Economy', 'Business', 'First']
for i, class_purchased in enumerate(fare_classes):
    for j, class_flown in enumerate(fare_classes):
        class_of_service_key = i * len(fare_classes) + j + 1
        purchased_flown_group = f'{class_purchased}-{class_flown}'
        class_change_indicator = 'Upgrade' if j > i else ('Downgrade' if j < i else 'No Class Change')
        cursor.execute("INSERT INTO Class_Of_Service_Flown_DimT VALUES (:1, :2, :3, :4, :5)", 
                       (class_of_service_key, class_purchased, class_flown, purchased_flown_group, class_change_indicator))
connection.commit()'''

In [63]:
# Populate Payment Method Dimension


'''payment_methods = ['Credit Card', 'Debit Card', 'Bank Transfer', 'PayPal','Cash']
for i, payment_method_name in enumerate(payment_methods, start=1):
    cursor.execute("INSERT INTO Payment_Method_DimT VALUES (:1, :2)", 
                   (i, payment_method_name))

connection.commit()'''

In [69]:
# Populate Passenger Dimension
from faker import Faker

'''# Create Faker instance
fake = Faker()

# Populate Passenger Dimension table
for i in range(1000):
    passenger_key = i + 1
    passport_number = f'PASS{i:06}'
    first_name = fake.first_name()
    last_name = fake.last_name()
    gender = random.choice(genders)
    nationality = random.choice(nationalities)
    email_address = f'{first_name.lower()}_{last_name.lower()}@example.com'
    date_of_birth = random_date(start_date - timedelta(days=36500), start_date - timedelta(days=3650))
    phone_number = f'123456789{i:03}'
    alive = random.choice(['Y', 'N'])
    cursor.execute("INSERT INTO Passenger_DimensionT VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10)", 
                   (passenger_key, passport_number, first_name, last_name, gender, nationality, email_address, date_of_birth, phone_number, alive))

In [71]:
# Define the list of passenger aircraft types

'''
passenger_aircrafts = [
    "Airbus A220",
    "Airbus A319", "Airbus A320",
    "Airbus A321", "Airbus A330","Airbus A340","Airbus A350",
    "Airbus A380", "Boeing 737", "Boeing 747","Boeing 757", "Boeing 767", "Boeing 777",  "Boeing 787 Dreamliner",
    "Bombardier CRJ Series",
    "Embraer E-Jet Series",
    "Embraer ERJ Series",
    "ATR 42","ATR 72","Sukhoi Superjet 100",
    "Mitsubishi Regional Jet (MRJ)","Comac ARJ21",
    "Tupolev Tu-204", "Antonov An-148",   "Irkut MC-21",
    "McDonnell Douglas MD-80 Series",
    "McDonnell Douglas MD-90 Series", "Fokker 70","Fokker 100", "Dassault Falcon 7X"
]

# Populate Aircraft Dimension table
for i, aircraft_type in enumerate(passenger_aircrafts, start=1):
    aircraft_id = i
    manufacturer = random.choice(['Boeing', 'Airbus'])
    manufacturer_date = random_date(start_date - timedelta(days=3650), start_date)
    no_of_seats_economy = random.randint(100, 200)
    no_of_seats_business = random.randint(20, 50)
    no_of_seats_first = random.randint(5, 15)
    max_capacity = no_of_seats_economy + no_of_seats_business + no_of_seats_first
    max_range = random.uniform(5000, 15000)
    fuel_capacity_in_liter = random.uniform(50000, 200000)
    engine_type = random.choice(['turbofan', 'turboprop', 'turbojet'])
    engine_manufacturer = random.choice(['GE Aviation', 'Rolls-Royce', 'Pratt & Whitney'])
    operating_weight = random.uniform(50000, 200000)
    max_takeoff_weight = random.uniform(100000, 500000)
    max_landing_weight = max_takeoff_weight
    cursor.execute("INSERT INTO Aircraft_DimensionT VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11, :12, :13, :14, :15)", 
                   (aircraft_id, aircraft_type, manufacturer, manufacturer_date, no_of_seats_economy, no_of_seats_business, no_of_seats_first, max_capacity, max_range, fuel_capacity_in_liter, engine_type, engine_manufacturer, operating_weight, max_takeoff_weight, max_landing_weight))

# Commit changes to the database
connection.commit()'''

In [73]:
# Populate Transaction Type Dimension
'''transaction_types = ['Eraned', 'Redeemed']
for i, transaction_type_name in enumerate(transaction_types, start=1):
    cursor.execute("INSERT INTO Transaction_Type_DimensionT VALUES (:1, :2)", 
                   (i, transaction_type_name))

# Commit changes to the database
connection.commit()'''

In [76]:
# Populate Transaction Type Dimension
'''
import csv

# Open the airports.csv file and read the data
with open('airports.csv', newline='', encoding='utf-8') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        airport_code = row['IATA']
        airport_name = row['Airport']
        city = row['City']
        country = row['Country']
        region = row['Region']
        latitude = float(row['Latitude'])
        longitude = float(row['Longitude'])
        airport_type = row['Type']
        airport_code_icao = row['ICAO']
        airport_contact_number = row['Contact']
        airport_email = row['Email']
        cursor.execute("INSERT INTO Airport_DimensionT VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11)", 
                       (airport_code, airport_name, city, country, region, latitude, longitude, airport_type, airport_code_icao, airport_contact_number, airport_email))

# Commit changes to the database
connection.commit() '''

In [85]:
#Fare_Basis_DimensionT

'''
# Define fare classes and types
fare_classes = ['Economy', 'prem. Economy', 'Business', 'First']
fare_types = ['Standard', 'Promotional']

# Initialize the starting key value
fare_basis_key = 1

# Function to generate fare basis code
def generate_fare_basis_code(fare_class, fare_type, min_stay_requirement):
    booking_class = fare_class[0]  # First letter of fare class
    fare_type_code = fare_type[:2].upper()  # First two letters of fare type (uppercase)
    return f"{booking_class}{min_stay_requirement}{fare_type_code}"

# Populate Fare Basis Dimension
for fare_class in fare_classes:
    for fare_type in fare_types:
        for min_stay_requirement in range(1, 31):  # Minimum stay requirement from 1 to 30 days
            fare_basis_code = generate_fare_basis_code(fare_class, fare_type, min_stay_requirement)
            cursor.execute("INSERT INTO Fare_Basis_DimensionT VALUES (:1, :2, :3, :4, :5)", 
                           (fare_basis_key, fare_basis_code, fare_class, fare_type, min_stay_requirement))
            fare_basis_key += 1  # Increment the key for each iteration

# Commit changes to the database
connection.commit()'''

In [86]:
#Partner_Service_DimensionT

'''
hotel_partners = ['Kempineski', 'Ramsis Hilton', 'Grand Hayat']
hotel_services = ['1 free Nights', '2 free Nights', '3 free Nights']

transportation_partners = ['Uber', 'Kareem', 'SWVL']
transportation_services = ['0-20 KM Ride', '21-40 KM Ride', '41-60 KM Ride']

retail_partners = ['carrefour', 'spinneys']
retail_services = ['20$ voucher', '50$ voucher', '60$ voucher']

# Function to generate a random partner service ID
def generate_partner_service_id():
    return random.randint(1000, 9999)

# Populate Partner Service Dimension
partner_service_key = 1  # Starting value for sequential surrogate key
for partner_type in ['hotel', 'Transportation', 'Retail']:
    if partner_type == 'hotel':
        partners = hotel_partners
        services = hotel_services
    elif partner_type == 'Transportation':
        partners = transportation_partners
        services = transportation_services
    elif partner_type == 'Retail':
        partners = retail_partners
        services = retail_services
    
    for partner_name in partners:
        for service_name in services:
            partner_service_id = generate_partner_service_id()
            cursor.execute("INSERT INTO Partner_Service_DimensionT VALUES (:1, :2, :3, :4, :5)", 
                           (partner_service_key, partner_service_id, service_name, partner_name, partner_type))
            partner_service_key += 1  # Increment the surrogate key

# Commit changes to the database
connection.commit()
'''

In [116]:
import random
# Populate Booking Channel Dimension table
'''
# Define function to generate random channel ID
def generate_random_channel_id():
    return random.randint(1, 1000)

# Define function to generate sequential surrogate key for Booking_Channel_Key
def generate_booking_channel_key(index):
    return index + 1

# Populate Booking Channel Dimension table
channels = ['mail', 'call', 'website', 'cash desk']
for i, channel_name in enumerate(channels):
    channel_id = generate_random_channel_id()
    booking_channel_key = generate_booking_channel_key(i)

    cursor.execute("INSERT INTO Booking_Channel_DimensionT (Booking_Channel_Key, Channel_ID, Channel_Name) VALUES (:1, :2, :3)",
                   (booking_channel_key, channel_id, channel_name))

# Commit changes to the database
connection.commit()
'''

In [156]:
import random
from datetime import timedelta

# Populate Flight Activity Fact table

'''
# Define function to generate random date key within the provided range
def generate_random_date_key(start_date, end_date):
    random_date = start_date + timedelta(days=random.randint(0, (end_date - start_date).days))
    return int(random_date.strftime('%Y%m%d'))

# Define function to generate random time key
def generate_random_time():
    hour = random.randint(0, 23)
    minute = random.randint(0, 59)
    second = random.randint(0, 59)
    return f"{hour:02d}:{minute:02d}:{second:02d}"

# Define function to generate random passenger key
def generate_random_passenger_key():
    return random.randint(1, 1000)

# Define function to generate random passenger profile key
def generate_random_passenger_profile_key():
    return random.randint(1, 100)

# Define function to generate random airport key
def generate_random_airport_key():
    return random.choice(['JFK', 'LHR', 'HND', 'CDG', 'SFO', 'PEK', 'DXB', 'AMS', 'FRA', 'ATL', 'ICN', 'LAX', 'ORD', 'DFW', 'DEN', 'CGK', 'BKK', 'SIN', 'CAN', 'SEA', 'LGA', 'HKG', 'MEX', 'MIA', 'YYZ', 'SYD'])

# Define function to generate random airplane key
def generate_random_airplane_key():
    return random.randint(1, 30)

# Define function to generate random service class key
def generate_random_service_class_key():
    return random.randint(1, 16)

# Define function to generate random fare basis code
def generate_random_fare_basis_code():
    return random.randint(1, 240)

# Define function to generate random booking channel key
def generate_random_booking_channel_key():
    return random.randint(1, 4)

# Populate Flight Activity Fact table
for _ in range(1000):
    scheduled_departure_date_key = generate_random_date_key(start_date, end_date)
    scheduled_departure_time_key = generate_random_time()
    actual_departure_date_key = generate_random_date_key(start_date, end_date)
    actual_gmt_departure_time_key = generate_random_time()
    scheduled_arrival_date_key = generate_random_date_key(start_date, end_date)
    scheduled_gmt_arrival_time_key = generate_random_time()
    actual_arrival_date_key = generate_random_date_key(start_date, end_date)
    actual_arrival_gmt_time_key = generate_random_time()
    passenger_key = generate_random_passenger_key()
    passenger_profile_key = generate_random_passenger_profile_key()
    start_airport_key = generate_random_airport_key()
    end_airport_key = generate_random_airport_key()
    airplane_key = generate_random_airplane_key()
    service_class_key = generate_random_service_class_key()
    fare_basis_code = generate_random_fare_basis_code()
    booking_channel_key = generate_random_booking_channel_key()
    confirmation_number = f'CONF{random.randint(1000, 9999)}'
    ticket_number = f'TICKET{random.randint(1000, 9999)}'
    flight_number = f'TICKET{random.randint(1000, 9999)}'
    segment_sequence_number = random.randint(1, 4)
    departure_time_delay = random.randint(0, 120)
    arrival_time_delay = random.randint(0, 120)
    base_fare_revenue = random.uniform(100, 1000)
    passenger_facility_charges = random.uniform(10, 100)
    airport_tax = random.uniform(10, 100)
    government_tax = random.uniform(10, 100)
    baggage_charges = random.uniform(0, 50)
    upgrade_fees = random.uniform(0, 100)
    transaction_fees = random.uniform(0, 50)
    segment_miles_flown = random.uniform(500, 5000)
    segment_miles_earned = random.uniform(500, 5000)

    # Modify the SQL statement with appropriate placeholders
    cursor.execute("INSERT INTO Flight_Activity_FactT VALUES (:1, TO_TIMESTAMP(:2, 'HH24:MI:SS'), :3, TO_TIMESTAMP(:4, 'HH24:MI:SS'), :5, TO_TIMESTAMP(:6, 'HH24:MI:SS'), :7, TO_TIMESTAMP(:8, 'HH24:MI:SS'), :9, :10, :11, :12, :13, :14, :15, :16, :17, :18, :19, :20, :21, :22, :23, :24, :25, :26, :27, :28, :29, :30, :31)", 
                   (scheduled_departure_date_key, scheduled_departure_time_key, actual_departure_date_key, actual_gmt_departure_time_key, scheduled_arrival_date_key, scheduled_gmt_arrival_time_key, actual_arrival_date_key, actual_arrival_gmt_time_key, passenger_key, passenger_profile_key, start_airport_key, end_airport_key, airplane_key, service_class_key, fare_basis_code, booking_channel_key, confirmation_number, ticket_number, flight_number, segment_sequence_number, departure_time_delay, arrival_time_delay, base_fare_revenue, passenger_facility_charges, airport_tax, government_tax, baggage_charges, upgrade_fees, transaction_fees, segment_miles_flown, segment_miles_earned))

# Commit changes to the database
connection.commit()
'''

In [130]:
import random
from datetime import timedelta

# Populate Reservation Fact table

'''
# Define function to generate random Flight ID from existing flight activity fact
def generate_random_flight_id():
    # Assume you have a list of flight IDs from the flight activity fact table
    # Replace this with your actual list of flight IDs
    flight_ids = ['FLIGHT1', 'FLIGHT2', 'FLIGHT3', 'FLIGHT4', 'FLIGHT5']
    return random.choice(flight_ids)

# Define function to generate random remaining seats for each class
def generate_random_remaining_seats():
    return random.randint(50, 200)  # Adjust the range as needed

# Define function to generate random unearned revenue
def generate_random_unearned_revenue():
    return random.uniform(1000, 10000)  # Adjust the range as needed

# Define function to generate random date key within the provided range
def generate_random_date_key(start_date, end_date):
    random_date = start_date + timedelta(days=random.randint(0, (end_date - start_date).days))
    return int(random_date.strftime('%Y%m%d'))

# Populate Reservation Fact table
for _ in range(1000):  # Adjust the number of rows as needed
    snapshot_date_key = generate_random_date_key(start_date, end_date)  # Use the function you defined
    departure_date_key = generate_random_date_key(start_date, end_date)  # Use the function you defined
    arrival_date_key = generate_random_date_key(start_date, end_date)  # Use the function you defined
    flight_id = generate_random_flight_id()
    remaining_seat_e = generate_random_remaining_seats()
    remaining_seat_prim_e = generate_random_remaining_seats()
    remaining_seat_b = generate_random_remaining_seats()
    remaining_seat_f = generate_random_remaining_seats()
    unearned_revenue = generate_random_unearned_revenue()

    cursor.execute("INSERT INTO Reservation_FactT (Flight_ID, Snapshot_Date_Key, Departure_Date_Key, Arrival_Date_Key, Remaining_Seat_E, Remaining_Seat_PRIM_E, Remaining_Seat_B, Remaining_Seat_F, Uneraned_Revenue) VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9)",
                   (flight_id, snapshot_date_key, departure_date_key, arrival_date_key, remaining_seat_e, remaining_seat_prim_e, remaining_seat_b, remaining_seat_f, unearned_revenue))

# Commit changes to the database
connection.commit()
'''

In [5]:
import random

# Populate Customer Care Fact table


# Define lists of valid keys from dimension tables (replace with your actual data)
'''
airport_codes = ['JFK', 'LHR', 'HND', 'CDG', 'SFO', 'PEK', 'DXB', 'AMS', 'FRA', 'ATL', 'ICN', 'LAX', 'ORD', 'DFW', 'DEN', 'CGK', 'BKK', 'SIN', 'CAN', 'SEA', 'LGA', 'HKG', 'MEX', 'MIA', 'YYZ', 'SYD']
interaction_date_keys = range(20150101, 20300101)
interaction_ID = range(1, 2160)
passenger_profile_keys = range(1, 121)
passenger_keys = range(1, 1001)
ancillary_service_ids = range(1, 13)
main_service_keys = range(1, 5)

# Populate Customer Care Fact table
for i in range(1000):
    leg_start_airport_key = random.choice(airport_codes)
    leg_end_airport_key = random.choice(airport_codes)
    while leg_end_airport_key == leg_start_airport_key:  # Ensure start and end airports are different
        leg_end_airport_key = random.choice(airport_codes)
    
    ticket_number = f'TICKET{random.randint(1000, 9999)}'
    aircraft_key = random.randint(1, 30)
    flight_number = f'FLIGHT{random.randint(1000, 9999)}'
    interaction_date_key = random.choice(interaction_date_keys)
    passenger_profile_key = random.choice(passenger_profile_keys)
    passenger_key = random.choice(passenger_keys)
    interaction_id = random.choice(interaction_ID)
    ancillary_service_id = random.choice(ancillary_service_ids)
    main_service_key = random.choice(main_service_keys)
    status = random.choice(['resolved', 'pending', 'escalated'])
    comments = f'Comments for interaction {i}'

    cursor.execute("INSERT INTO Customer_Care_FactT VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11, :12, :13)", 
                   (leg_start_airport_key, leg_end_airport_key, ticket_number, aircraft_key, flight_number, interaction_date_key, passenger_profile_key, passenger_key, interaction_id, ancillary_service_id, main_service_key, status, comments)) 

# Commit changes to the database
connection.commit()
'''

In [7]:
import random

# Populate Flight Ancillary Points Fact table

'''
# Define lists of valid keys from dimension tables (replace with your actual data)
passenger_keys = range(1, 1001)
passenger_profile_keys = range(1, 121)
ancillary_service_keys = range(1, 13)
transaction_date_keys = range(20150101, 20300101)
payment_method_keys = range(1, 6)  # Assuming 5 payment methods

# Populate Flight Ancillary Points Fact table
for i in range(1000):
    passenger_key = random.choice(passenger_keys)
    passenger_profile_key = random.choice(passenger_profile_keys)
    ancillary_service_key = random.choice(ancillary_service_keys)
    transaction_date_key = random.choice(transaction_date_keys)
    payment_method_key = random.choice(payment_method_keys)
    ticket_number = f'TICKET{random.randint(1000, 9999)}'
    transaction_type = random.choice(['Earned', 'Redeemed'])
    no_of_points = random.randint(1, 100)
    Ancillary_service_cost = random.uniform(10, 500)

    cursor.execute("INSERT INTO Flight_Ancillary_Points_FactT VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9)", 
                   (passenger_key, passenger_profile_key, ancillary_service_key, transaction_date_key, payment_method_key, ticket_number, transaction_type, no_of_points, Ancillary_service_cost)) 

# Commit changes to the database
connection.commit()'''

In [162]:
import random
# Populate Partner Points Fact table

'''
# Define lists of valid keys from dimension tables (replace with your actual data)
passenger_keys = range(1, 1001)
passenger_profile_keys = range(1, 121)
partner_service_keys = range(1, 21)
transaction_date_keys = range(20150102, 20300101)
payment_method_keys = range(1, 6)  # Assuming 5 payment methods

# Populate Partner Points Fact table
for i in range(1000):
    passenger_key = random.choice(passenger_keys)
    passenger_profile_key = random.choice(passenger_profile_keys)
    partner_service_key = random.choice(partner_service_keys)
    transaction_date_key = random.choice(transaction_date_keys)
    payment_method_key = random.choice(payment_method_keys)
    transaction_id = f'TRANS_{random.randint(1000, 9999)}'
    transaction_type = random.choice(['Earned', 'Redeemed'])
    no_of_points = random.randint(1, 100)
    partner_service_cost = random.uniform(10, 500)

    cursor.execute("INSERT INTO Partner_Points_FactT VALUES (:1, :2, :3, :4, :5, :6, :7, :8, :9)", 
                   (passenger_key, passenger_profile_key, partner_service_key, transaction_date_key, payment_method_key, transaction_id, transaction_type, no_of_points, partner_service_cost)) 

# Commit changes to the database
connection.commit()
'''

In [163]:
# Commit the changes and close the connection
cursor.close()
connection.close()

print("Data populated successfully!")

Data populated successfully!